"""
Django settings for huoshan_deepseek project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b6k-64@$y$vl8hkc)tn$fi)gm*gyc+o-og+znz5)x**h4z69+e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

#Celelry配置
CELERY_BROKER_URL = 'redis://localhost:6379/0'#使用Redis作为消息代理
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'#使用Redis作为结果存储
CELERY_ACCEPT_CONTENT = ['json']#指定接受的内容类型
CELERY_TASK_SERIALIZER = 'json'#指定任务序列化器
CELERY_RESULT_SERIALIZER = 'json'#指定结果序列化器
CELERY_TIMEZONE = 'UTC'#指定时区

CELERY_IMPORTS = (
    'llmserverapp.tasks',
)

ASGI_APPLICATION = 'huoshanhs_ds_server.asgi.application'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [('127.0.0.1',6379)],#redis服务地址
        }
    }
}
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#             "capacity": 1000,  # 调整容量
#             "channel_capacity": {
#                 "specific_channel_name": 200,  # 为特定通道设置容量
#             },
#         },
#     },
# }

# CORS
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS=[
    "http://127.0.0.1:5173",
    "http://localhost:5173",
    "null"#前端直接点击html文件时，是以file:///形式打开的，此时origin就为Null，易导致CORS ERROR
]
CORS_ORIGIN_WHITELIST = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
    "null"
]

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET', 
    'OPTIONS', 
    'PATCH', 
    'POST', 
    'PUT',
    'VIEW'
) 

CORS_ALLOW_HEADERS = (
    'accept', 
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with'
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'llmserverapp',
    'corsheaders',
    'rest_framework',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hs_ds_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hs_ds_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
